In [2]:
import numpy as np
np.__version__

'1.19.5'

# Creating NumPy Arrays

In [3]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###### There are lots of built-in ways to generate Arrays
    Arange
    zeros and ones
    Linspace
    Random
        Rand
        Randn
        randint

## arange

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros and ones

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## Random
Numpy also has lots of ways to create random number arrays:


 1) Rand
 2) Randn
 3) randint

### rand

In [15]:
np.random.rand(2)

array([0.35716982, 0.33579334])

In [16]:
np.random.rand(5,5)

array([[0.03322494, 0.70599157, 0.73858495, 0.38782871, 0.69916428],
       [0.03762997, 0.41106036, 0.66197441, 0.65524612, 0.75761381],
       [0.56284906, 0.55630429, 0.02884838, 0.86569976, 0.92305672],
       [0.57182541, 0.94177698, 0.45632159, 0.51730728, 0.32997221],
       [0.16756253, 0.16248072, 0.90260639, 0.51031086, 0.02124724]])

### randn

In [17]:
np.random.randn(2)

array([2.23561969, 1.21243923])

In [18]:
np.random.randn(5,5)

array([[ 1.17410673, -0.04181627,  0.45982233, -0.59873732, -0.17667368],
       [ 1.28445387,  1.98893408,  1.01344124, -1.62528678,  0.53772078],
       [-1.71767539, -1.42375562,  0.11097285, -0.66226359,  0.08534502],
       [ 0.7932285 , -0.66864811, -0.99499135,  0.11599777, -0.62494929],
       [ 0.93384567, -0.81058466,  1.25043997, -1.21954465, -0.29455059]])

### randint

In [19]:
np.random.randint(1,100)

77

In [20]:
np.random.randint(1,100,10)

array([54, 80, 27,  1, 37, 63, 70, 34, 51,  9])

## Array Attributes and Methods

### reshape

In [21]:
arr= np.arange(25)

In [22]:
arr.shape

(25,)

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [25]:
arr.reshape(1,25).shape

(1, 25)

In [26]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [27]:
arr.dtype

dtype('int32')

### max,min,argmax,argmin

In [28]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 7, 18, 17, 36, 30,  1, 33, 14, 13, 19])

In [29]:
ranarr.min()

1

In [30]:
ranarr.max()

36

In [31]:
ranarr.argmax()

3

In [32]:
ranarr.argmin()

5

# numpy indexing and selection

### Bracket Indexing and Selection

In [33]:
arr= np.arange(0,11)

In [34]:
arr[8]

8

In [35]:
arr[1:5]

array([1, 2, 3, 4])

In [36]:
arr[0:5]

array([0, 1, 2, 3, 4])

### broadcasting

In [37]:
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [39]:
#not a good idea

In [40]:
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [42]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [43]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [44]:
#still change numpy array

In [45]:
arr= np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Indexing a 2D array (matrices)

In [49]:
arr_2rd = np.array(([[1,2,3],[4,5,6],[7,8,9]]))
arr_2rd

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr_2rd[1]

array([4, 5, 6])

###### arr_2rd[row][col]

In [51]:
arr_2rd[1][0]

4

In [52]:
arr_2rd[1,0]

4

In [53]:
#2D array slicing

In [54]:
arr_2rd[:2,1:]

array([[2, 3],
       [5, 6]])

In [55]:
arr_2rd[2]

array([7, 8, 9])

In [56]:
arr_2rd[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

### Selection with condition

In [57]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

## numpy operations - arithmetic

In [59]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [61]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [62]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [63]:
arr / arr

C:\Users\USER\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [64]:
1 / arr

C:\Users\USER\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [65]:
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [66]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [67]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [68]:
np.min(arr)

0

In [69]:
np.max(arr)

9

In [70]:
np.add(2,2)

4

In [71]:
np.subtract(9,3)

6

In [72]:
np.multiply(3,5)

15

In [73]:
np.divide(8,4)

2.0